#pragma once

#define APP_VERSION "4.0.0";
#define TWAI_TX_GPIO 25
#define TWAI_RX_GPIO 26
#define ENGINE_POWER_GPIO 14
#define CAMERA_POWER_GPIO 13

#define IMU_INT_GPIO 17
#define IMU_SPI_CS_GPIO 15
#define IMU_WAKE_GPIO 33
#define IMU_RST_GPIO 16
#define IMU_SPI_SCK 18
#define IMU_SPI_MISO_GPIO 19
#define IMU_SPI_MOSI_GPIO 23
#define IMU_SPI_SPEED 3000000U

#define I2C_SDA 21
#define I2C_SCL 22
#define I2C_SPEED 400000U

#define CAN_PLATFORM_QUATERNION 0x10
#define CAN_PLATFORM_ACCELEROMETER 0x11
#define CAN_PLATFORM_GYROSCOPE 0x12
#define CAN_PLATFORM_ACCURACY 0x13
#define CAN_PLATFORM_BAROMETER 0x14

#define CAN_SHOULDER_QUATERNION 0x20
#define CAN_SHOULDER_ACCELEROMETER 0x21
#define CAN_SHOULDER_GYROSCOPE 0x22
#define CAN_SHOULDER_ACCURACY 0x23
#define CAN_SHOULDER_SET_YZ_DEGREE 0x24
#define CAN_SHOULDER_SET_ROTATE_RADIAN 0x25